### ISSUE TITLE
experiment mode door bug

### ISSUE THREAD

**Issue by M-goofy** [studio-minus/madness-interactive-reloaded#239] opened 2024-09-15 10:33 UTC
**Describe the bug**
in experiment door when playing around with autospawn for a bit one of the doors in this tiny room stays open on will not let u through 

**Steps to reproduce**
1. go to experiment mode
2. enable autospawn(of course with some enemies)
3. play for a bit in the disco room or the wide room with the sky background
4. when entering in that tiny room(the one in the screenshots) will have one of the doors that will be buggeg 

**Screenshots or video**

![Screenshot (39)](https://github.com/user-attachments/assets/c29ee19d-3424-4dbb-aa07-03131c3960a8)
![Screenshot (40)](https://github.com/user-attachments/assets/1962e44b-104a-43e5-921e-7e2391e70d96)

**Desktop (please complete the following information):**
 - OS: windows 11   64 bit
 - Version 0.49.0 (happened in olso other recent versions)

**Additional context**
DOOR STUCK!

**Comment by mestiez** [comment] 2024-09-15 13:18
Duplicate of #168

**Closed by mestiez** 2024-09-15 13:18 UTC
Labels: bug
