### ISSUE TITLE
the wounds are just lines

### ISSUE THREAD

**Issue by RandomChild559** [studio-minus/madness-interactive-reloaded#356] opened 2024-10-26 19:27 UTC
**Describe the bug**
when you shoot someone there is no gunshot wounds and it just puts lines.

**Steps to reproduce**
1. shoot a guy

**Expected behavior**
there are no gunshot wounds, when i shoot someone it has the blood splatter effect but it just spawns some lines on the guy and not gunshot wounds

**Screenshots or video**
![image](https://github.com/user-attachments/assets/399d403d-c4d5-4ff9-a83c-ae513346a787)

**Desktop (please complete the following information):**
 - OS: windows
 - Version 0.49.4

**Additional context**
i tried this on many versions the same thing happened

**Comment by mestiez** [comment] 2024-10-26 19:32
Duplicate of #54

**Closed by mestiez** 2024-10-26 19:32 UTC
Labels: bug

**Comment by pxbsaa** [comment] 2024-11-11 15:06
atp fucking developers ignorong thi shit
