### ISSUE TITLE
Visual glitches + crashes

### ISSUE THREAD

**Issue by NK-523** [studio-minus/madness-interactive-reloaded#45] opened 2024-09-06 21:44 UTC
The map of the rooftop, is off, I think, and the game crashes if you die on it or progress and sometimes if you leave or tab in.

**Steps to reproduce**
It seems a bit random, but if you go to rooftop_01, or 02, I think, and do any of the aforementioned actions, it could crash. And of course the whole thing of the whole map being off. Although, the crash seems to happen more if you progress into the level a bit, and then die or leave. I haven't tested leaving or tabbing in too much, however.

**Expected behavior**

**Screenshots or video**
![image](https://github.com/user-attachments/assets/1be5cc21-13a8-4e28-b5db-d959174f9a6e)
![image](https://github.com/user-attachments/assets/199816bc-95a0-4123-8091-65af5b9ea89c)

https://github.com/user-attachments/assets/c2d63761-68a6-422b-bce0-2a527a9bfade

Here is a screenshot of the crash from the video.

![image](https://github.com/user-attachments/assets/7fa073dd-674f-4aa6-a6ef-67a2cdf3cb77)

**Desktop (please complete the following information):**
Windows 11, ver 48.3, prebuilt.

**Additional context**
I have quite a few crash logs open, if you need them, just tell me, I can and will provide them. I just don't want to bloat this initial message. I also haven't tested this enough, and the crashing may also apply to levels after the levels I mentioned, or even before, and this is just a rare, already mentioned bug, that I've just had awful luck with. I will give my first crash, which happened when progressing to the next level. 
![image](https://github.com/user-attachments/assets/a7526435-9ab8-4a54-8487-58aa7aef4242)
This is more to help development, and I'm positive you already know this is a thing, but if there's more reports, it's assured it isn't a one-off bug.

**Comment by Ninjakaiden523** [comment] 2024-09-06 21:55
I just realized, the rest of the crash logs are exactly the same, so maybe sharing them would be useless.

**Comment by mestiez** [comment] 2024-09-07 09:56
Duplicate of #37

**Closed by mestiez** 2024-09-07 09:56 UTC
Labels: bug
