### ISSUE TITLE
DJ Flashing in Experiment

### ISSUE THREAD

**Issue by iternetidiot** [studio-minus/madness-interactive-reloaded#291] opened 2024-09-23 04:40 UTC
In the experiment stage, the DJ flashes out of existence for a few frames before re-apearring.

The issue appears to be that his animation resets at the incorrect time, causing a few frames where he just isn't there.

 - OS: [Windows]
 - Version [10.22]

**Comment by mestiez** [comment] 2024-09-23 13:31
Duplicate of #44

**Closed by mestiez** 2024-09-23 13:31 UTC
Labels: bug
