### ISSUE TITLE
flying breaks getting on the train

### ISSUE THREAD

**Issue by RazLooa** [studio-minus/madness-interactive-reloaded#317] opened 2024-10-02 08:16 UTC
**The Bug:**
while using the Jebus disk (or whatever its called i dont remember), on the train section, attempting to get on the train whilst flying soft-locks the player, forcing a restart.

**Reproduction of The Bug:**
1. enable the Jebus Disk (the one that lets you fly)
2. go to the level stated in the video
3. fly
4. attempt to get onto the train

**what was expected to happen?**
i expected to get on the train, perhaps with a floatier animation or something, nothing happened, then when i stopped flying, i couldnt progress and i had to restart, so i instead of restarting made a bug-report, and video.

**Screenshots or video**
If applicable, add media to help explain your problem.

**Desktop**
 - OS: [Windows 10 Pro]
 - Version [22H2]

**Additional context**
i was playing on 0.49.3 (the new one)
sorry if the video is low quality, first time using OBS

https://github.com/user-attachments/assets/c8446b1a-ac2f-4de3-87fc-4fddcdac0f43

**Comment by mestiez** [comment] 2024-10-02 08:54
Duplicate of #277

**Closed by mestiez** 2024-10-02 08:54 UTC
Labels: bug
