### ISSUE TITLE
The "Menagerie" Improbability Disk breaks the lvl_roof_1 and lvl_roof_2's enemy spawning.

### ISSUE THREAD

**Issue by NikoForever** [studio-minus/madness-interactive-reloaded#237] opened 2024-09-15 01:40 UTC
**Describe the bug**
Using the "Menagerie" Improbability Disk on either of these levels prevents enemies from spawning (except ones placed on level start), making impossible to proceed on lvl_roof_1 (since no more enemies spawn after you kill the first ones) and impossible to win the Mag Rich boss fight since you can't do enough damage to Rich before you run out of guns.

**Steps to reproduce**
1. Activate "Menagerie" Improbability Disk 
2. Load either the levels lvl_roof_1 or lvl_roof_2
3. No enemies will spawn afterwards

**Expected behavior**
Entering the levels with this Improbability Disk activated won't break the enemy spawning system and prevent level progression.

**Screenshots or video**
![image](https://github.com/user-attachments/assets/5c15a45f-24d1-49ad-93ba-4bac7847ade5)
![image](https://github.com/user-attachments/assets/bfcb73f1-c97c-4c4d-949a-8cc83cc753bb)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 23H2

**Additional context**
1. This doesn't happen with the "Ghost Protocol" Improbability Disk, only the "Menagerie" one.

**Comment by mestiez** [comment] 2024-09-15 10:01
Duplicate of #94

**Closed by mestiez** 2024-09-15 10:01 UTC
Labels: bug
