### ISSUE TITLE
"static"

### ISSUE THREAD

**Issue by giuseppe1231** [studio-minus/madness-interactive-reloaded#219] opened 2024-09-14 02:46 UTC
im playing normal the first level and this 

i dont know what is this
![image](https://github.com/user-attachments/assets/41276a5e-fd64-4841-bea2-c9ab891cac30)

**Comment by mestiez** [comment] 2024-09-14 13:42
Duplicate of #194

**Closed by mestiez** 2024-09-14 13:42 UTC
Labels: bug
