### ISSUE TITLE
still having the ghost ragdolls bug

### ISSUE THREAD

**Issue by M-goofy** [studio-minus/madness-interactive-reloaded#177] opened 2024-09-10 19:43 UTC
**Describe the bug**
in some levels the ghosts ragdolls are still there

**Steps to reproduce**
1. clrear a room
2. enter the next room
3. there will be a change the ghost ragdoll could appear

**Screenshots or video**

![Screenshot (13)](https://github.com/user-attachments/assets/cacaf3f4-0b0e-4e6a-9bf4-f528ea955630)
![Screenshot (16)](https://github.com/user-attachments/assets/3403c711-e809-47ce-89d8-8fe3a222723b)
![Screenshot (14)](https://github.com/user-attachments/assets/3b231037-f65e-427f-a55b-b6c7b59e4b3a)

**Desktop (please complete the following information):**
 - windows 64 bit
 - Version 0.48.7

**Comment by mcduckpop** [comment] 2024-09-11 04:29
You have the same problem as me

**Comment by mrmadnezz** [comment] 2024-09-11 17:51
Happens for me too, the only fix i found is to just die and restart the level.

**Comment by mestiez** [comment] 2024-12-17 13:24
Duplicate of #36

**Closed by mestiez** 2024-12-17 13:24 UTC
Labels: bug
