### ISSUE TITLE
no bullet gore 

### ISSUE THREAD

**Issue by M-goofy** [studio-minus/madness-interactive-reloaded#186] opened 2024-09-11 13:00 UTC
**Describe the bug**
when i shot at someone there is no bullet gore effect, but there are blood splaters, melee wounds and blood stains on walls

**Screenshots or video**

![Screenshot (18)](https://github.com/user-attachments/assets/4de6fd01-34aa-4f1c-9d75-e28174300bed)

**Desktop (please complete the following information):**
 - windows 11 64 bit
 - Version 0.48.7

**Comment by mestiez** [comment] 2024-09-11 14:24
Duplicate of #54

**Closed by mestiez** 2024-09-11 14:24 UTC
Labels: bug
