### ISSUE TITLE
No background in roof and in boss fight

### ISSUE THREAD

**Issue by JustANormalGuyyy** [studio-minus/madness-interactive-reloaded#97] opened 2024-09-07 20:14 UTC
When i reached in roof theres no background but i continued...
when i reached in boss when im die and try to restart the game just crash soo please repair it

thats all!!!11!1

**Comment by SoapFif** [comment] 2024-09-07 21:04
how do they even forget abt this lmao

**Comment by grandmafighterjet** [comment] 2024-09-07 21:04
idk

**Comment by mestiez** [comment] 2024-09-07 23:07
Duplicate of #37

**Closed by mestiez** 2024-09-07 23:07 UTC
Labels: bug
