### ISSUE TITLE
lvl-roof and boss fight floor not rendering (Employee of the Month Campaign)

### ISSUE THREAD

**Issue by quiteuncivilized** [studio-minus/madness-interactive-reloaded#155] opened 2024-09-09 07:09 UTC
I am unsure whether this is meant to be on purpose, but the floor on the roof level and boss fight doesn't render.

**Steps to reproduce**
1. Completed elevator level
2. lvl-roof loads
This also happens if I select the level through the level select.
**Expected behavior**
As I mentioned before, I am unsure whether this is meant to be this way.

**Screenshots or video**
![Screenshot 2024-09-09 170413](https://github.com/user-attachments/assets/7c123d4f-385f-4de9-918a-959a5f47eb0b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version [0.48.4]

**Additional context**
Nil

**Comment by dch-GH** [comment] 2024-09-09 07:24
This shouldn't be happening anymore. Are you using the latest version `v0.48.5-beta`?
https://github.com/studio-minus/madness-interactive-reloaded/releases/tag/v0.48.5-beta

**Comment by mestiez** [comment] 2024-09-09 14:28
Duplicate of #37

**Closed by mestiez** 2024-09-09 14:28 UTC
Labels: bug
