### ISSUE TITLE
No background during the roof bossfight.

### ISSUE THREAD

**Issue by mrmadnezz** [studio-minus/madness-interactive-reloaded#96] opened 2024-09-07 20:02 UTC
**Describe the bug**
When you enter the roof, there is no background

**Steps to reproduce**
1. Simply play the roof levels.

**Expected behavior**
Expected the background to be there

![dsadasdhsa](https://github.com/user-attachments/assets/4a7bba56-3b55-44e8-9daf-981d5742bd92)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Its just basically really annoying.

**Comment by mestiez** [comment] 2024-09-07 23:07
Duplicate of #37

**Closed by mestiez** 2024-09-07 23:07 UTC
Labels: bug
