### ISSUE TITLE
Is it normal that gore and blood stains are still not exist on newer versions

### ISSUE THREAD

**Issue by TeomanDeniz** [studio-minus/madness-interactive-reloaded#218] opened 2024-09-14 00:03 UTC
**Describe the bug**
Gores and blood stains like bullet holes on bodies are not exist. Is this normal on newer versions? Or is it just me?

If it is just me, I guess I have missing additional .NET libraries installed in my operating system lol

**Expected behavior**
Seeing bloody bullet holes when shooting grunts. But it's works for melee weapons like swords or knives.

**Screenshots or video**

https://github.com/user-attachments/assets/2c66958c-c6d7-495b-81fe-4af6b55cbf96

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Version [e.g. 0.49.0]

**Comment by mestiez** [comment] 2024-09-14 13:43
Duplicate of #54

**Closed by mestiez** 2024-09-14 13:43 UTC
Labels: bug

**Comment by pxbsaa** [comment] 2024-10-10 17:08
tf u mean duplicated of 54 just give us explanation
