### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TeomanDeniz** [studio-minus/madness-interactive-reloaded#87] opened 2024-09-07 16:52 UTC
**Describe the bug**
At the `lvl_roof_1[038]`, I noticed the room's background texture is not loaded. After I killed everyone, game is crashed.

**Steps to reproduce**
1. Start at `lvl_elevator[037]` room
2. After finishing the room, just go to the next room (`lvl_roof_1[038]`).

**Screenshots or video**
![image](https://github.com/user-attachments/assets/0f8c78d1-3de8-43a7-a64e-511690f1e2c3)

**Desktop:**
 - **OS:** Windows 11
 - **Game build:** MIR, Version=0.48.3.0
 - **Engine build:** Walgelijk, Version=0.29.0.0

**Additional context**
# Crash Log:

## Unhandled exception occurred
```
System.NullReferenceException: Object reference not set to an instance of an object.
```

## Stack trace
```
   at Walgelijk.OpenTK.OpenTKGraphics.Delete(Object obj) in C:\Projects\Walgelijk\Walgelijk.OpenTK\Graphics\OpenTKGraphics.cs:line 247
   at Walgelijk.RenderTexture.Dispose() in C:\Projects\Walgelijk\Walgelijk\Graphics\RenderTexture.cs:line 117
   at MIR.StampCanvasComponent.Dispose() in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Graphics\Components\StampCanvasComponent.cs:line 94
   at Walgelijk.FilterComponentCollection.InternalRemoveComponent(Component component) in C:\Projects\Walgelijk\Walgelijk\ECS\Components\FilterComponentCollection.cs:line 267
   at Walgelijk.FilterComponentCollection.SyncBuffers() in C:\Projects\Walgelijk\Walgelijk\ECS\Components\FilterComponentCollection.cs:line 250
   at Walgelijk.Scene.Dispose() in C:\Projects\Walgelijk\Walgelijk\ECS\Scene.cs:line 414
   at Walgelijk.Game.set_Scene(Scene value) in C:\Projects\Walgelijk\Walgelijk\System\Game.cs:line 56
   at MIR.MadnessUtils.<>c__DisplayClass24_1.b__1() in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Shared\MadnessUtils.cs:line 309
   at MIR.MadnessUtils.<>c__DisplayClass25_0.<g__delay|0>d.MoveNext()
   at Walgelijk.RoutineScheduler.g__advance|5_0(<>c__DisplayClass5_0&) in C:\Projects\Walgelijk\Walgelijk\System\RoutineScheduler.cs:line 82
   at Walgelijk.RoutineScheduler.StepRoutines(Single dt) in C:\Projects\Walgelijk\Walgelijk\System\RoutineScheduler.cs:line 78
   at Walgelijk.Game.Start() in C:\Projects\Walgelijk\Walgelijk\System\Game.cs:line 263
   at MIR.MadnessInteractiveReloaded..ctor() in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\MadnessInteractiveReloaded.cs:line 211
   at MIR.Program.Main(String mode, String input, String output) in C:\Projects\madness-interactive-reloaded\src\MadnessInteractiveReloaded\Program.cs:line 56
```

**Comment by mestiez** [comment] 2024-09-07 23:09
Duplicate of #37

**Closed by mestiez** 2024-09-07 23:09 UTC
Labels: bug
