### ISSUE TITLE
Door Is Broken

### ISSUE THREAD

**Issue by Takua-The-Tohunga** [studio-minus/madness-interactive-reloaded#260] opened 2024-09-18 18:30 UTC
**Describe the bug**
Door Is Broken

**Steps to reproduce**
1. Leave Experiment Meaney Times
2. ???

**Expected behavior**
DOOR THAT WONT OPEN!

**Screenshots or video**

https://github.com/user-attachments/assets/cb8f4bde-93d2-4bc2-b6f8-33e1efe6530c

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [beta 0.49.0]

~~Additional context~~

**Comment by mestiez** [comment] 2024-09-18 20:59
Duplicate of #168

**Closed by mestiez** 2024-09-18 20:59 UTC
Labels: bug
