### ISSUE TITLE
I can't climb up the ladder.

### ISSUE THREAD

**Issue by RealAdrian1** [studio-minus/madness-interactive-reloaded#302] opened 2024-09-26 16:29 UTC
**Describe the bug**
So when i hold space it still doesn't climb up the ladder.

**Steps to reproduce**
Don't have any

**Expected behavior**
Climbing the ladder.

**Screenshots or video**
![image](https://github.com/user-attachments/assets/be673a5a-3cbc-4791-8912-c662bd65d0ea)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.491

**Additional context**
Can yall fix that?

**Comment by mestiez** [comment] 2024-09-26 19:40
Duplicate of #134

**Closed by mestiez** 2024-09-26 19:40 UTC
Labels: bug
