### ISSUE TITLE
2 major bugs including the final scene of the train and roof levels.

### ISSUE THREAD

**Issue by krmwinner** [studio-minus/madness-interactive-reloaded#90] opened 2024-09-07 17:18 UTC
the train engine wont blow up when i use disks and the tricky disk makes it so u get softlocked when u die to mag rich at the edge of the roof.

the train engine should explode when shot at all occasions, and the tricky respawn location should be set to the spawn point of that level.

 - OS: Windows

**Comment by mestiez** [comment] 2024-09-07 23:09
Duplicate of #37 and #49

**Closed by mestiez** 2024-09-07 23:09 UTC
Labels: bug
