### ISSUE TITLE
Game crashes upon continuing a completed campaign [Linux]

### ISSUE THREAD

**Issue by EmDotRand** [studio-minus/madness-interactive-reloaded#354] opened 2024-10-25 08:58 UTC
**Describe the bug**
After completing a campaign, the continue button remains. Pressing it crashes the game.

**Steps to reproduce**
1. Boot the game on a Linux based system using WINE.
2. Complete a campaign. (The tutorial was used to confirm the bug.)
3. Return to the campaign menu.
4. Select the completed campaign. The game should crash.

**Expected behavior**
One of:
- Starting from the last completed level.
- The start button replacing the continue button, allowing for restarting of campaign.

**Screenshots or video**
N/A : Crash

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64 
 - Kernel: Linux 6.11.3-arch1-1
 - Game Version 0.49.4

**Additional context**
- Component Dump: [mir_Schoe_components.md](https://github.com/user-attachments/files/17519221/mir_Schoe_components.md)
- System Dump: [mir_Schoe_systems.md](https://github.com/user-attachments/files/17519222/mir_Schoe_systems.md)

**Comment by CrowbarFBI** [comment] 2024-10-26 10:42
Use Wine 9.0

**Comment by mestiez** [comment] 2024-10-26 19:34
Very likely a duplicate of #332

**Closed by mestiez** 2024-10-26 19:34 UTC
Labels: bug

**Comment by EmDotRand** [comment] 2024-10-26 21:39
If it's fixed, would you link to the commit that solved that issue? Would save from more duplicates in the future.

**Comment by mestiez** [comment] 2024-10-27 14:40
My bad, it's because #332 is actually a duplicate of #323 but it seems that I forgot to mention that.
