### ISSUE TITLE
telekinesis bug: telekinesis can´t be deactivated

### ISSUE THREAD

**Issue by Abs0lv3d0r** [studio-minus/madness-interactive-reloaded#229] opened 2024-09-14 17:23 UTC
telekinesis activates and stays activated until player exits the room, it happens when you´re using "savior" drive or "phantom madness", both anyways, i just press the key to deactivate the power but it it won't budge, this afects the guns causing all of them to point to the ground and SHOOT to the ground irreversibly(until player gets out of the room) . tried swords and blunt and they work fine, no problem btw. see guys if look guys if that helps i have more bug reports to do. cya.

Edit: Sorry for my bad english, i don´t speak this language normally.

**Comment by mestiez** [comment] 2024-09-15 10:00
Duplicate of #213

**Closed by mestiez** 2024-09-15 10:00 UTC
Labels: bug
