### ISSUE TITLE
The hands don't appear 

### ISSUE THREAD

**Issue by GustavoLeaoSuperPro** [studio-minus/madness-interactive-reloaded#247] opened 2024-09-16 23:41 UTC
I simply open the game, wait for the loading, when finishes, my character don't have hands, this happen to all enemys, some hands appear (and it is only for enemy), but i can't continue my progress, i can't exit from the third screen because of this bug. The bug make me don't give hit the enemy.

I expected it to work in my pc

![image](https://github.com/user-attachments/assets/587ed391-897d-4baa-b348-f3aa1c1afd34)

 OS Windows 10 Pro 64 bits
 Version 0.49.0

I dont know what to do, i don't know to program games, programs, etc. I think my pc is a problem too

Geforce 9600 GT (this is old, oh shit)
Pentium Dual Core
16 GB Ram
HD 160 gb 💀

(and a little edit, i am from Brazil so if my english is bad, i have to swear google translate and my studies)

**Comment by mestiez** [comment] 2024-09-17 10:03
Duplicate of #38

**Closed by mestiez** 2024-09-17 10:03 UTC
Labels: bug
