### ISSUE TITLE
enemies not spawning on lvl_roof_1

### ISSUE THREAD

**Issue by TheGamer3840** [studio-minus/madness-interactive-reloaded#165] opened 2024-09-09 20:01 UTC
**Describe the bug**
I was testing the new version until at level lvl_roof_1 only 4 agents came out instead of many more enemies starting to come out, I think it will be the Menagerie imporvability disk since I was using that disk

**Steps to reproduce**
probably use the Menagerie disk at level lvl_roof_1

**Expected behavior**
I expected more enemies to appear instead of 4

**Screenshots or video**
![image](https://github.com/user-attachments/assets/fcaeba91-3b45-493a-be30-e8ee5f5fd9f6)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version  21H2

**Comment by mestiez** [comment] 2024-09-09 20:17
Duplicate of #94

**Closed by mestiez** 2024-09-09 20:17 UTC
Labels: bug
