### ISSUE TITLE
Weird blood texture on gunshots?

### ISSUE THREAD

**Issue by CplusQ** [studio-minus/madness-interactive-reloaded#382] opened 2024-11-25 16:13 UTC
I think it might be just me? because i watched other playthroughs and the blood looked normal.
![Uploading Screenshot 2024-11-25 110341.png…]()

**Comment by mestiez** [comment] 2024-11-25 17:25
You didn't upload an image, but this is very likely a duplicate of #263

**Closed** 2024-11-27 11:03 UTC
Labels: bug, invalid
