### ISSUE TITLE
No bullet decals on game

### ISSUE THREAD

**Issue by pmbsaa** [studio-minus/madness-interactive-reloaded#309] opened 2024-09-30 17:56 UTC
**Describe the bug**
Gore bug

**Steps to reproduce**
1. opensgamr
2. shoots guy
3. has no blood gore
4. only blood lines that's it

**Expected behavior**
can't have bullet gores 😔 

not have screenshot yet but yeah

Laptop
 - OS: [Windows 11 (PRO)]
 - Version [e.g. 0.49.1-beta]

**Additional context**

**Comment by mestiez** [comment] 2024-09-30 19:24
Duplicate of #54

**Closed by mestiez** 2024-09-30 19:24 UTC
Labels: bug
