### ISSUE TITLE
Background image corruption lvl depths and tubes

### ISSUE THREAD

**Issue by Abs0lv3d0r** [studio-minus/madness-interactive-reloaded#278] opened 2024-09-21 03:54 UTC
Every once in a while these white Chopsticks, sprites or WHATEVER THEY ARE, appear out of nowhere in lvl level depths and pipes, they're almost always the only things that ruin the background, the rest is fine.

*expected behaviour*:
GET RID OF ´EM

*Aditional information*
 would like to take a screenshot of the game but it changes alternating between the loading screen and the game, I'm using lightshot anyway. or maybe im too stoopid to do it

**Comment by mestiez** [comment] 2024-09-22 09:59
It would be nice to have a screenshot because I have no idea what you mean

**Comment by Abs0lv3d0r** [comment] 2024-09-23 00:35
![imagen_2024-09-22_213504619](https://github.com/user-attachments/assets/6188d2bf-ac31-4990-a7d3-c7af2c62fcef)
here

**Comment by SacredSven** [comment] 2024-09-23 13:16
this looks to be image corruption to me. You should probably rename your issue to "Background Image Corruption".

**Comment by mestiez** [comment] 2024-09-26 19:47
Duplicate of #194

**Closed by mestiez** 2024-09-26 19:47 UTC
Labels: bug, invalid
