### ISSUE TITLE
Dodging on bridge breaks trigger

### ISSUE THREAD

**Issue by CheeseDealerUno** [studio-minus/madness-interactive-reloaded#208] opened 2024-09-13 11:53 UTC
**Describe the bug**
As the title suggests, doding on the bridge right before the trigger to enter the train seems to cause the trigger to vanish.

**Steps to reproduce**
It's absurdly easy to pull off.
If you dodge forward at about where my character is in the image, it'll freak out and break the trigger.
![image](https://github.com/user-attachments/assets/65c29e0f-058e-48b9-91ab-f37599527b4a)

Here's a video showing it happen in real time;
https://github.com/user-attachments/assets/c49d599c-21a5-45a2-b017-3d6348a44e0c

**Desktop:**
 - OS: Windows
 - Version 0.48.8

**Comment by SacredSven** [comment] 2024-09-13 13:18
This may be due to the Dodging interrupting the triggered animation, from what i've seen.

**Comment by mestiez** [comment] 2024-09-13 14:33
Duplicate of #7

**Closed by mestiez** 2024-09-13 14:33 UTC
Labels: bug
