### ISSUE TITLE
Black background error and crashes on lvl_roof_1 and lvl_roof_2

### ISSUE THREAD

**Issue by Dilopho-Mos** [studio-minus/madness-interactive-reloaded#56] opened 2024-09-07 05:52 UTC
**Describe the bug**
lvl_roof_1 and lvl_roof_2 have the backgrounds completely black, characters spawn out of thin air on specific spots, which I asume has to do something with there being no backgrounds. Dying or closing the game will cause it to crash, and bring

**Steps to reproduce**
1.- Entering lvl_roof_1 and lvl_roof_2.

**Expected behavior**
I expected to see what I asume to be a rooftop?

**Screenshots or video**
The following is a picture of how it looks like:
![image](https://github.com/user-attachments/assets/0efa413c-bc63-4262-990a-051087b6fb7f)

These are the error screens I've had so far:
![image](https://github.com/user-attachments/assets/ef7bad3a-0457-4322-880a-dc18e081f441)
![image](https://github.com/user-attachments/assets/a561aefe-9581-40ed-9adb-6a9f35c1e916)
![image](https://github.com/user-attachments/assets/a790a3be-2e51-4261-a5eb-7347bbcf15d6)
![image](https://github.com/user-attachments/assets/7795b763-f412-442a-b0a2-35cc54175708)
![image](https://github.com/user-attachments/assets/ffa76152-2c8d-463d-a8cc-f70b60b672f0)
![image](https://github.com/user-attachments/assets/597e7269-b9e1-4575-a9ab-147a6f5f8a29)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 Home Single Language

**Additional context**
I've found that quitting back to the menu sometimes avoids the crash entirely.

**Comment by ThatExplo** [comment] 2024-09-07 07:03
+1

**Comment by mestiez** [comment] 2024-09-07 09:56
Duplicate of #37

**Closed by mestiez** 2024-09-07 09:56 UTC
Labels: bug
