### ISSUE TITLE
game literally does not open 

### ISSUE THREAD

**Issue by maggain** [studio-minus/madness-interactive-reloaded#157] opened 2024-09-09 10:14 UTC
**Describe the bug**
Did all the exact steps to download it, turned off my antivirus, even ran as administrator, absolutely nothing happens.

**Expected behavior**
Game opens, hooray.

**Screenshots or video**
Someone else has already posted a video with the exact same problem, literally the same.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version: 22H2
**Additional context**
Thats it, jus' doesnt work

**Comment by EEASAS** [comment] 2024-09-09 15:43
i'm having same problem

**Comment by civinum** [comment] 2024-09-11 13:00
Try troubleshooting the exe. always works for me

**Comment by mestiez** [comment] 2024-09-22 11:07
Duplicate of #125

**Closed by mestiez** 2024-09-22 11:07 UTC
Labels: bug
