### ISSUE TITLE
Level bug - my game will crash when I pass the first part of the roof level, or if I die on the roof level.

### ISSUE THREAD

**Issue by aeioyouxt54** [studio-minus/madness-interactive-reloaded#91] opened 2024-09-07 17:26 UTC
game crashes whenever i die or pass the first part of the roof level, opens up something that says how i want to open this file.

**Comment by mestiez** [comment] 2024-09-07 23:07
Duplicate of #37

**Closed by mestiez** 2024-09-07 23:07 UTC
Labels: bug
