### ISSUE TITLE
no gore and bullet wounds present but sword slash it´s activated

### ISSUE THREAD

**Issue by Abs0lv3d0r** [studio-minus/madness-interactive-reloaded#230] opened 2024-09-14 17:47 UTC
never seen bullet wounds in MY game, it is my specs? i mean, gore it´s always on the game but i didn´t see a single bullet wound in GAME. not even the grunts, agents, nor engineer, not even the soldats. at least i want a way to fix this manually or something like that because seeing other people having gore activated in their gameplay not mine makes me envy them.  haven't found the solution yet but if you help me I would appreciate it. byee!

**Comment by mestiez** [comment] 2024-09-15 10:00
Duplicate of #54

**Closed by mestiez** 2024-09-15 10:00 UTC
Labels: bug
