### ISSUE TITLE
Ghost bodies

### ISSUE THREAD

**Issue by Apopooyelpoy** [studio-minus/madness-interactive-reloaded#133] opened 2024-09-08 12:42 UTC
in the campaign, specifically more noticeable in the train part, with stamp bodies on background on, when you go to a new vagon, you'll see ragdoll "Ghosts" in the background

**Comment by dch-GH** [comment] 2024-09-09 04:52
What graphics card are you using? Are you on a laptop using integrated graphics?

**Comment by mestiez** [comment] 2024-12-17 13:24
Duplicate of #36

**Closed by mestiez** 2024-12-17 13:24 UTC
Labels: bug
