### ISSUE TITLE
latter softlock

### ISSUE THREAD

**Issue by M-goofy** [studio-minus/madness-interactive-reloaded#221] opened 2024-09-14 09:56 UTC
**Describe the bug**
  i get softlocked in the latter level when re-playing the campain for a second time

**Screenshots or video**

![Screenshot (32)](https://github.com/user-attachments/assets/6fd2cf79-90f6-46f5-b926-6ad6979984b5)
![Screenshot (34)](https://github.com/user-attachments/assets/6b099ee7-87d4-495a-9210-43a959594fb8)

**Desktop (please complete the following information):**
 - OS: windows 11 64 bit
 - Version 0.49.0

**Comment by mestiez** [comment] 2024-09-14 13:43
Duplicate of #134

**Closed by mestiez** 2024-09-14 13:43 UTC
Labels: bug
