### ISSUE TITLE
Auditor bug

### ISSUE THREAD

**Issue by AlmaTray** [studio-minus/madness-interactive-reloaded#64] opened 2024-09-07 11:42 UTC
**Describe the bug**
Auditor's fire particles are flickering at the end of the animation

**Steps to reproduce**
1. Enable the HP disk

**Expected behavior**
The dark flames are expected to loop properly

**Desktop**
 - Windows 11
 - Version: 0.48.3

**Comment by mestiez** [comment] 2024-09-07 12:46
Duplicate of #44

**Closed by mestiez** 2024-09-07 12:46 UTC
Labels: bug
