### ISSUE TITLE
my character has no hands

### ISSUE THREAD

**Issue by SwissCheese047** [studio-minus/madness-interactive-reloaded#175] opened 2024-09-10 17:22 UTC
**Describe the bug**
my character has no hands and so dont the enemies. the attack animations still play but i cant kill, and so cant the enemies. i can spawn in guns in experiment mode, but when they hit the ground, they just disappear, and i cant pick them up after they disappeared (no shit). when i move the gun (or melee weapon, i tried both) to my character and press e and close the spawnmenu, however, will just lag the game a lot. i can still shoot, and whilst the lag is happening, my character's hands show up for a second. only fix is quitting the experiment mode, pressing Tab to open the spawning menu, or opening the console. but after closing the console and the spawn menu, it will continue the lag. when i spawn in a gun or an enemy, it just spams "[ WRN ] Over 100000 steps (Raycast)" in the console. 

**Steps to reproduce**
1. start the game
2. menu character has no hands
3. play game
4. cant attack, cant be attacked

**Expected behavior**
i expected the character to have hands and that i can attack people. turns out nah.

**Screenshots or video**
pictures:
![image](https://github.com/user-attachments/assets/4805d806-7881-4a8b-b49c-6a8058e2fd70)
![image](https://github.com/user-attachments/assets/56e323c1-6f57-479d-b3f1-9c0ead367d29)
i think he is fine
![image](https://github.com/user-attachments/assets/fff29673-0dc3-4a67-9bde-c90bf6c10332)
videos:
https://github.com/user-attachments/assets/32dbcc21-25af-4669-a279-a4c5f80da5da
https://github.com/user-attachments/assets/8a3d4695-a9fe-4f27-abb5-a0683eb39f3c

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version: 0.48.9

**Additional context**
game buggy

**Comment by mestiez** [comment] 2024-09-11 10:12
Duplicate of #38

**Closed by mestiez** 2024-09-11 10:12 UTC
Labels: bug
