### ISSUE TITLE
Enemy body damaged effect does not work

### ISSUE THREAD

**Issue by Louiess** [studio-minus/madness-interactive-reloaded#156] opened 2024-09-09 09:30 UTC
**Describe the bug**
Enemy body damaged effect does not work, but enemy armor shatter and detach effect works fine
**Steps to reproduce**
1. N/A

**Expected behavior**
Enemy should have bullet holes in their body when shot, which do not appear
**Screenshots or video**
![Screenshot 2024-09-09 022102](https://github.com/user-attachments/assets/90849dd1-4cfb-46e7-a972-ac09a762c2c7)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 0.48.5
 - Graphic card RTX 4070 on laptop

**Additional context**
None

**Comment by mestiez** [comment] 2024-09-09 14:29
Duplicate of #54

**Closed by mestiez** 2024-09-09 14:29 UTC
Labels: bug
