### ISSUE TITLE
Instead of bullet wounds I get odd strings of blood, I also get no gore, just them falling over with little odd bits of blood 

### ISSUE THREAD

**Issue by SillyLittleGoobor** [studio-minus/madness-interactive-reloaded#407] opened 2024-12-26 06:39 UTC
![Screenshot 2024-12-25 233037](https://github.com/user-attachments/assets/f076ac5f-c8e8-42a8-90cb-7e7b387abf71)
Example

**Comment by Dikkiedink** [comment] 2024-12-27 11:07
duplicate of #263

**Closed by Dikkiedink** 2024-12-27 11:07 UTC
Labels: bug
