### ISSUE TITLE
Train Cutscene Glitch

### ISSUE THREAD

**Issue by SacredSven** [studio-minus/madness-interactive-reloaded#277] opened 2024-09-20 23:45 UTC
**Describe the bug**
Breaks the cutscene of when you get on the Train.

**Steps to reproduce**
1. Go to the Train Level.
2. Dodge right before you get into the cutscene
3. Enter the cutscene
4. Watch it all go wrong.

**Expected behavior**
I expected the train cutscene not to break.

**Screenshots or video**[
https://youtu.be/GgwW9toa7yY

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 0.49.1

**Additional context**
I only started recording after the glitch/bug happened.

**Comment by dch-GH** [comment] 2024-09-22 20:37
Duplicate of https://github.com/studio-minus/madness-interactive-reloaded/issues/273

**Comment by LatteImACheater** [comment] 2024-09-24 10:17
> > Duplicate of #273
> 
> This was done without the disks, Only with base dodging. Also, when it glitched, I respawned to the right.

It was done without the disks but atleast you got respawned but if you do it with disks you will be soft-locked  in the level

**Comment by SacredSven** [comment] 2024-09-24 12:50
> > > Duplicate of #273
> > 
> > 
> > This was done without the disks, Only with base dodging. Also, when it glitched, I respawned to the right.
> 
> It was done without the disks but atleast you got respawned but if you do it with disks you will be soft-locked in the level

Lol, it was busted. I still couldn't progress.

**Closed** 2024-10-02 09:37 UTC
Labels: bug
